### ISSUE TITLE
数据包重载时存在报错

### ISSUE THREAD

**Issue by Pau1am** [JackHaozhu/Minecraft-Survival-Datapack#1]
当我在服务端输入指令"/reload"的时候，后台日志显示以下内容:

`[Worker-Main-5/ERROR]: Couldn't load tag universal_dyeing:dyes as it is missing following references: #universal_dyeing:dyes (from file/CraftingDatapack-v2.2.zip)`

游戏版本为1.20.1

**Comment by YamaArashiHZ** [comment]
使用最新的release可以解决
